### ISSUE TITLE
[BUG] Unable to create a new environment

### ISSUE THREAD

**Issue by msmygit** [datastax/astra-cli#103]
**Describe the bug**

While attempting to leverage the latest feature from `0.4` release to create a non-prod environment, I ran into the following error,
<details>
  <summary>Expand/Collapse stacktrace</summary>

  ```
   % astra config create msdev --token AstraCS:CHANGE_ME --env DEV
   [ERROR] You provided an invalid value for option. (-option)
   [ERROR] Environment: can not convert "DEV" to a AstraEnvironment (ParseOptionConversionException)
   [ERROR] Try 'astra help <your_command>' to get help
  ```
</details>

**To Reproduce**

See the steps provided in the description.

**Expected behavior**
A new environment is created with the specified name.

**Screenshots**
n/a

**Desktop (please complete the following information):**
- OS: MacOS
- Version: Ventura `13.5.1`

**Additional context**
n/a

**Comment by clun** [comment]
**Error reason:**
`--env XX` was not marshall as an expected `AstraEnvironment`

More validate 

```console
./target/astra config create issue_dev2 --token <token> --env integration
[ERROR] You provided an invalid value for option. (-option)
[ERROR] Invalid option value (--env), expecting [PROD, DEV, TEST] (ParseRestrictionViolatedException)
[ERROR] Try 'astra help <your_command>' to get help
```
