### ISSUE TITLE
[BUG] Astra CLI doesn't recognize databases above 25 to be queried via cqlsh

### ISSUE THREAD

**Issue by dram-ds** [datastax/astra-cli#123]
**Describe the bug**

Astra CLI doesn't recognize databases above 25 to be queried via cqlsh

https://github.com/datastax/astra-sdk-java/blob/main/astra-sdk-devops/src/main/java/com/dtsx/astra/sdk/db/domain/DatabaseFilter.java#L30

**Comment by clun** [comment]
The limit ash been extended to `100` with the SDK. The fix will be integrating in next release
