### ISSUE TITLE
Support for Apple ARM M2 Pro chip 

### ISSUE THREAD

**Issue by pedrocassalpacheco** [datastax/astra-cli#169]
**Describe the bug**

Unable run astra-cli on said platform

**To Reproduce**

Follow instructions on READ.md on a Apple M2 Pro mac. Response:

The current machine does not support all of the following CPU features that are required by the image: [CX8, CMOV, FXSR, MMX, SSE, SSE2, SSE3, SSSE3, SSE4_1, SSE4_2, POPCNT, LZCNT, AVX, AVX2, BMI1, BMI2, FMA].

**Expected behavior**
Run astra-cli on mac

**Screenshots**

**Desktop (please complete the following information):**
- OS: MacOS
- Version Ventura 3.10

**Additional context**

**Comment by clun** [comment]
This platform is supported. 

Could you please detailed you installation procedure ? We woud update documentation.
Make sure you are using homebrew for M Chips.
