### ISSUE TITLE
Dotenv creation should preserve pre-existing extraneous env var definitions

### ISSUE THREAD

**Issue by hemidactylus** [datastax/astra-cli#22]
**Current behaviour**
At the moment (v0.1.1), if you have a `.env` already with your own var definitions, `create-dotenv` overwrites it.

**Use case:**
We may have other env vars we want to have in the final, complete dotenv (extraneous to astra but needed by the app).

Ideally the `create-dotenv` might take care of preserving env var definitions that do not overlap with those it creates.

This would make it easier to end up with a final `.env` such as:

```
MY_SETTING="abc"
NUMBER_OF_FRZSQQY="123"
ASTRA_DB_APPLICATION_TOKEN="AstraCS:..."
# (other AstraDB stuff ...)
```

something that at the moment is achieved with a supplementary file and a `cat XXX >> .env` afterwards.
This comes up now and then e.g. in workshops.

**Implementation**
I wouldn't be so fussy about preserving empty lines, comments, ordering and the like. As long as it satisfies the above it's good enough as a first version.

(then, perhaps later, it could "remember" the location of pre-existing Astra DB env vars and preserve it, plus appending at the end with a prefix comment those that did not appear previously, or something like that. But that's secondary)

**Comment by clun** [comment]
This update makes a lot of sense. If the file already exists, existing keys will be preserved.

**Comment by clun** [comment]
Actually the code was doing some extra steps to filters the keys. The behaviour has been updated and will be part of `0.2`
