### ISSUE TITLE
[BUG] Installing the CLI breaks the SDKMAN autocompletion 

### ISSUE THREAD

**Issue by nicoloboschi** [datastax/astra-cli#24]
After installing the astra cli, the sdkman autocompletion doesn't work anymore

```
#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

#THIS MUST BE AT THE END OF THE FILE FOR ASTRA_CLI TO WORK!!!
export ASTRADIR="/Users/nicolo.boschi/.astra/cli"
[[ -s "/Users/nicolo.boschi/.astra/cli/astra-init.sh" ]] && source "/Users/nicolo.boschi/.astra/cli/astra-init.sh"
```

Commenting the astra cli initialization script, sdkman gets back to work

I suppose the astra-init.sh overrides some functions that are in the sdkman init as well

**Comment by clun** [comment]
`astra-init.sh` is generated from the framework for autocompletion, the only rows added are 

```
autoload -U +X compinit > /dev/null 2>&1 && compinit
autoload -U +X bashcompinit > /dev/null 2>&1 && bashcompinit
```

I do have both working on my machine at the same time. (shell bash)

**Comment by clun** [comment]
I am not able to reproduce the conditions. Could it be related to your work on pulsar-shell ? Can you try from a "fresh" machine ?

![Screenshot 2023-04-07 at 08 49 30](https://user-images.githubusercontent.com/726536/230557231-85228210-2b0c-45cb-832b-2cb5cad237f3.png)

I tried in a gitpod and also it is good.
