### ISSUE TITLE
cli fails to run on linux when installed through homebrew

### ISSUE THREAD

**Issue by tjake** [datastax/astra-cli#28]
**Describe the bug**

cli fails to run on linux when installed through homebrew

**To Reproduce**

1. brew install datastax/astra-cli/astra-cli
2. astra setup
3. Shows error: `exec format error: astra`

**Desktop (please complete the following information):**
- OS: [e.g. Linux]
- Version [e.g. Ubuntu 20.04]

**Comment by msmygit** [comment]
@tjake what is the OS and version of Linux where it fails?

**Comment by clun** [comment]
It should be working now. Version `0.2.1` 

For homebrew, the installation points to a portable java version working on all system. 

```
brew upgrade datastax/astra-cli/astra-cli
```
