### ISSUE TITLE
[BUG] Misleading error message when downloading SCB for name-colliding databases

### ISSUE THREAD

**Issue by hemidactylus** [datastax/astra-cli#32]
If one has more than one DB with the same name, running

```
astra db download-scb -f aaa.zip $DB
```

gives the error for the "Create database" operation, namely `[ERROR] ALREADY_EXIST: Cannot create another Database with name 'workshops' Use flag --if-not-exist to connect to the existing database`.

This message should be more accurate (and perhaps hint at the fact that you can specify a database by ID).

**Comment by clun** [comment]
Exception `DatabaseNameNonUnique` and `DatabasenameAlreadyExist` have been split to differentiates the situations.

`astra db download-scb  demo`

Will get you a
```
[ERROR] CONFLICT: Multiple databases with same name 'demo' detected. Please fallback to database id to resolve the conflict
```

`astra db create  demo`

Will get you a
```
[ERROR] ALREADY_EXIST: A database with name 'demo' already exists in the organization. To prevent conflicts CLI will not create another one, please change name
```
