### ISSUE TITLE
[BUG] (minor!) Color messed up after installation

### ISSUE THREAD

**Issue by hemidactylus** [datastax/astra-cli#34]
**Describe the bug**

Colorful output during the ` ... | bash` installation process (v0.2) seems to be missing a closing control char: when installation finishes the terminal has light-grey text (it was originally black). Reproduced a few times.

(bash on debian 10, fwiw)

**To Reproduce**

Check the terminal is printing in its default color, then run `curl -Ls "https://dtsx.io/get-astra-cli" | bash` and check again.

![astra-cli-greyification](https://user-images.githubusercontent.com/14221764/211423170-c564403f-2441-49e7-8c18-21b05306b02f.png)

**Comment by hemidactylus** [comment]
The above is seen using the "mate-terminal" terminal emulator - which offers profiles and redefinition of terminal color palette (so my "light grey" might be someone else's dark blue, [whatever](https://en.wikipedia.org/wiki/Inverted_spectrum) ).

Still, the console is left in a different status after installation due to what looks like an unmatched color control char.

**Comment by clun** [comment]
Fix was to reset color pattern at exit with either `$(tput sgr0)` or `tput init`
