### ISSUE TITLE
[BUG] `streaming get <tenant>` return ERROR You provided unknown or not well formatted argument.

### ISSUE THREAD

**Issue by PatBStream** [datastax/astra-cli#38]
Astra CLI command "`stra streaming get <tenant>` returns errors.

Installed Astra CLI version 0.2 on Windows 11 WSL2 terminal (Ubuntu 20.04 LTS)  

After setup and adding my token, "astra streaming list" works fine.  "astra streaming get <tenantname>" returns errors.

```
prompt@DESKTOP:~$ astra streaming get aws-useast1
[ERROR] You provided unknown or not well formatted argument.
[ERROR] Found unexpected parameters: [aws-useast1] (ParseArgumentsUnexpectedException)
[ERROR] Try 'astra help <your_command>' to get help**_
```

**Desktop (please complete the following information):**
Windows 11 WSL2 terminal (Ubuntu 20.04 LTS)

**Comment by clun** [comment]
**Diagnostic:**
Class `AbstractStreamingCmd` was not included in `reflect-congi.json` used for native compilation. All commands astra streaming exist/delete/pulsar-token would trigger the same error.

**Fix**
```json
 {
    "name":"com.dtsx.astra.cli.streaming.AbstractStreamingCmd",
    "allDeclaredFields":true
  }
```
