### ISSUE TITLE
[Feature] Support CDC endpoints

### ISSUE THREAD

**Issue by ddieruf** [datastax/astra-cli#4]
It would be nice to be able to GET/DELETE/POST to CDC endpoints. Here's an example POST
```bash
curl -X POST ${WEB_SERVICE_URL}/admin/v3/astra/tenants/${TENANT}/cdc \
  --header "Authorization: ${TOKEN}" \
  --header "X-DataStax-Pulsar-Cluster: ${CLUSTER_NAME}" \
  --data '{
  "databaseId": "'${DB_ID}'",
  "databaseName": "'${DB_NAME}'",
  "keyspace": "'${KEYSPACE_NAME}'",
  "orgId": "'${ORG_ID}'",
  "tableName": "'${TABLE_NAME}'",
  "topicPartitions": 3
}'
```

And an example GET

```bash
curl -X GET ${WEB_SERVICE_URL}/admin/v3/astra/tenants/${TENANT}/cdc \
  --header "Authorization: ${TOKEN}" \
  --header "X-DataStax-Pulsar-Cluster: ${CLUSTER_NAME}"
```

**Comment by clun** [comment]
I agree @ddieruf  can you point me to the documentation, it was not available the 2 times I asked for it to Chris

**Comment by clun** [comment]
During my tests a couple of addition.

- The Webservice URL is the one from the tenant as such for GET

```
https://{{pulsarCluster}}.api.streaming.datastax.com/admin/v3/astra/tenants/{{targetTenantName}}/cdc
```

Another Header is not required

```
X-DataStax-Pulsar-Cluster
X-DataStax-Current-Org
```
```

**Comment by clun** [comment]
This post will trace the progress 

#### Listing cdc for a tenant

- `astra streaming list-cdc clun-gcp-east1`

<img width="984" alt="Screenshot 2023-02-27 at 23 23 59" src="https://user-images.githubusercontent.com/726536/221699751-64937741-f554-4105-8dcb-0c7e556a225d.png">

#### Listing cdc for a db

- `astra db list-cdc db2`
<img width="1136" alt="Screenshot 2023-02-27 at 23 25 26" src="https://user-images.githubusercontent.com/726536/221699926-74cfda0a-d2d4-488a-bb29-b216883398c6.png">
