### ISSUE TITLE
[BUG] Astra cli fails when installed in Macos via homebrew

### ISSUE THREAD

**Issue by caiobrentano** [datastax/astra-cli#55]
**Describe the bug**

I followed the step-by-step Astra CLI documentation linked in the "Connect" tab on Astra UI. After installing it with `brew install datastax/astra-cli/astra-cli`, the second step is to run `astra setup` which fails with LinkageError. See below.

**To Reproduce**

```bash
(prod) ~ % astra setup
Error: LinkageError occurred while loading main class com.dtsx.astra.cli.AstraCli
	java.lang.UnsupportedClassVersionError: com/dtsx/astra/cli/AstraCli has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
(prod) ~ % astra --version
Error: LinkageError occurred while loading main class com.dtsx.astra.cli.AstraCli
	java.lang.UnsupportedClassVersionError: com/dtsx/astra/cli/AstraCli has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
(prod) ~ %
```

**Expected behavior**
The command should work as expected or throw a user-friendly error message with helpful information on how to fix it.

**Desktop (please complete the following information):**
- OS: MacOS (13.2.1 (22D68))
- Version: stable 0.2.1

**Comment by clun** [comment]
Thank you for the feedback.

**The cause:**
Homebrew installation should have installed Java17 and uses it, it seems your main Java is still older.

**Unblocking you**:
Install a JDK17+

** Fixing the error**
This error is outside of the project itself, we will work to see how those errors can be trapped and converted with a proper error message.

**Comment by clun** [comment]
Start script has been updated accordingly

Java Installation Check
```bash
if type -p java > /dev/null; then
    _java=java
elif [[ -n "$JAVA_HOME" ]] && [[ -x "$JAVA_HOME/bin/java" ]];  then
    _java="$JAVA_HOME/bin/java"
else
    echo Java has not been found. Java17+ is required to run astra-cli installed with homebrew
fi
```

Java17 Check
```bash
 if [[ "$version" > "16" ]]; then
        cd "$ASTRA_HOME"
        source $ASTRA_HOME/libexec/astra-init.sh
        java -jar $ASTRA_HOME/libexec/astra-cli.jar "$@"
    else
        echo Java17+ is required to run astra-cli but "$version" was used, please update
    fi
```
