### ISSUE TITLE
[BUG] astra db create-dotenv does not create .env file

### ISSUE THREAD

**Issue by synedra** [datastax/astra-cli#67]
**Describe the bug**

On my Macintosh, `astra db create-dotenv workshops -k gotest` does not create a .env file in my directory.

Weirdly, it works correctly on GitHub.

**To Reproduce**

`astra db create-dotenv workshops -k gotest`   --- no .env
`astra db create-dotenv workshops -k gotest --directory `pwd``  --- works 

**Expected behavior**
I expect the .env file to be created

**Desktop (please complete the following information):**
- OS: OSX Catalina
- 
- **Additional context**

**Comment by clun** [comment]
This issue happens with the CLI installed with brew. The command is running in `/usr/local/Cellar/astra-cli/0.3/bin/astra` and this is where the files are created. As you stated the workaround is to provide the fill path until i fix.

```
astra db create-dotenv workshops -k gotest --directory pwd``
```
